---
# Copyright 2016, Rackspace US, Inc.
#
# (C) 2016 Michael Rice <michael.rice@rackspace.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Ensure adjutant specific roles
  keystone:
    command: "ensure_role"
    role_name: "{{ item }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    endpoint: "{{ keystone_service_adminurl }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  with_items:
    - "project_admin"
    - "project_mod"
  no_log: True

- name: Ensure adjutant user
  keystone:
    command: "ensure_user"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    user_name: "{{ adjutant_service_user_name }}"
    domain_name: "{{ adjutant_user_domain_name }}"
    password: "{{ adjutant_service_password }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  no_log: True

- name: Add adjutant user to service admin role
  keystone:
    command: "ensure_user_role"
    user_name: "{{ adjutant_service_user_name }}"
    project_name: "service"
    role_name: "admin"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    endpoint: "{{ keystone_service_adminurl }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  no_log: True

- name: Ensure adjutant service
  keystone:
    command: "ensure_service"
    service_name: "{{ adjutant_service_name }}"
    service_type: "{{ adjutant_service_type }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    endpoint: "{{ keystone_service_adminurl }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 2
  no_log: True

- name: Ensure adjutant endpoints
  keystone:
    command: "ensure_endpoint"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    region_name: "{{ adjutant_service_region }}"
    service_name: "{{ adjutant_service_name }}"
    service_type: "{{ adjutant_service_type }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
    endpoint_list:
          - url: "{{ adjutant_service_publicurl }}"
            interface: "public"
          - url: "{{ adjutant_service_internalurl }}"
            interface: "internal"
          - url: "{{ adjutant_service_adminurl }}"
            interface: "admin"
  register: add_endpoint
  until: add_endpoint|success
  retries: 5
  delay: 10
  no_log: True
